spring:
  servlet:
    multipart:
      # 配置单个文件最大上传大小
      max-file-size: 5MB
      # 配置单个请求最大上传大小(一次请求可以上传多个文件)
      max-request-size: 40MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lqd31415926
    url: jdbc:mysql://mysql:3306/rizao

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8080

#spring 事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug